### ISSUE TITLE
The plugin doesn’t work with Ubuntu

### ISSUE THREAD

**Issue by guillaume8375** [oskretc/fman-sublimehelper#2]
I’ve just installed fman on Ubuntu 18.04 and I have Sublime Text build 3176. I installed fman-sublimehelper and set the path to Sublime Text to `/usr/bin/subl`.

When I use the plugin to try to open a file in Sublime Text, I get the follow error message:

```
Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 101, in _execute_command
  File "/home/guillaume/.config/fman/Plugins/Third-party/fman-sublimehelper/sublime_helper/__init__.py", line 38, in __call__
    openCommand(option, chosen_files, path)
  File "/home/guillaume/.config/fman/Plugins/Third-party/fman-sublimehelper/sublime_helper/__init__.py", line 118, in openCommand
    stdin=DEVNULL, stdout=DEVNULL, stderr=DEVNULL, env=env)
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1289, in _execute_child
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: "/usr/bin/subl   '/home/guillaume/Téléchargements/essai.sh'"
```

I could have done something wrong, though.

**Comment by guillaume8375** [comment]
The problem comes from Sublime Text, not fman-sublimehelper. It worked when I linked it to the snap version of Sublime Text.

**Comment by oskretc** [comment]
Glad it's working for you. I don't have Linux experience, so any feedback that could improve this plugin for Linux its very much welcome
